export const mockData = [
  {
    adult: false,
    backdrop_path: "/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg",
    id: 866398,
    title: "The Beekeeper",
    original_language: "en",
    original_title: "The Beekeeper",
    overview:
      "One man’s campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
    poster_path: "/A7EByudX0eOzlkQ2FIbogzyazm2.jpg",
    media_type: "movie",
    genre_ids: [28, 53, 18],
    popularity: 790.755,
    release_date: "2024-01-10",
    video: false,
    vote_average: 7.261,
    vote_count: 1182,
  },
  {
    adult: false,
    backdrop_path: "/cnqwv5Uz3UW5f086IWbQKr3ksJr.jpg",
    id: 572802,
    title: "Aquaman and the Lost Kingdom",
    original_language: "en",
    original_title: "Aquaman and the Lost Kingdom",
    overview:
      "Black Manta seeks revenge on Aquaman for his father's death. Wielding the Black Trident's power, he becomes a formidable foe. To defend Atlantis, Aquaman forges an alliance with his imprisoned brother. They must protect the kingdom.",
    poster_path: "/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg",
    media_type: "movie",
    genre_ids: [28, 12, 14],
    popularity: 852.854,
    release_date: "2023-12-20",
    video: false,
    vote_average: 6.898,
    vote_count: 1705,
  },
  {
    adult: false,
    backdrop_path: "/yyFc8Iclt2jxPmLztbP617xXllT.jpg",
    id: 787699,
    title: "Wonka",
    original_language: "en",
    original_title: "Wonka",
    overview:
      "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
    poster_path: "/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
    media_type: "movie",
    genre_ids: [35, 10751, 14],
    popularity: 1341.409,
    release_date: "2023-12-06",
    video: false,
    vote_average: 7.195,
    vote_count: 2157,
  },
  {
    adult: false,
    backdrop_path: "/A0EqMM4WZpzfxpdoDoqICCpzSQ1.jpg",
    id: 609681,
    title: "The Marvels",
    original_language: "en",
    original_title: "The Marvels",
    overview:
      "Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.",
    poster_path: "/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
    media_type: "movie",
    genre_ids: [878, 12, 28],
    popularity: 1159.02,
    release_date: "2023-11-08",
    video: false,
    vote_average: 6.283,
    vote_count: 1753,
  },
  {
    adult: false,
    backdrop_path: "/pwGmXVKUgKN13psUjlhC9zBcq1o.jpg",
    id: 634492,
    title: "Madame Web",
    original_language: "en",
    original_title: "Madame Web",
    overview:
      "Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.",
    poster_path: "/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg",
    media_type: "movie",
    genre_ids: [878, 28, 12],
    popularity: 1264.699,
    release_date: "2024-02-14",
    video: false,
    vote_average: 5.447,
    vote_count: 152,
  },
  {
    adult: false,
    backdrop_path: "/nTPFkLUARmo1bYHfkfdNpRKgEOs.jpg",
    id: 1072790,
    title: "Anyone But You",
    original_language: "en",
    original_title: "Anyone But You",
    overview:
      "After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
    poster_path: "/yRt7MGBElkLQOYRvLTT1b3B1rcp.jpg",
    media_type: "movie",
    genre_ids: [35, 10749],
    popularity: 611.822,
    release_date: "2023-12-21",
    video: false,
    vote_average: 6.936,
    vote_count: 448,
  },
  {
    adult: false,
    backdrop_path: "/4l65BWqJBl7hBwdIwp2nQdwsOuw.jpg",
    id: 850165,
    title: "The Iron Claw",
    original_language: "en",
    original_title: "The Iron Claw",
    overview:
      "The true story of the inseparable Von Erich brothers, who made history in the intensely competitive world of professional wrestling in the early 1980s. Through tragedy and triumph, under the shadow of their domineering father and coach, the brothers seek larger-than-life immortality on the biggest stage in sports.",
    poster_path: "/nfs7DCYhgrEIgxKYbITHTzKsggf.jpg",
    media_type: "movie",
    genre_ids: [18, 36],
    popularity: 284.586,
    release_date: "2023-12-21",
    video: false,
    vote_average: 7.5,
    vote_count: 226,
  },
  {
    adult: false,
    backdrop_path: "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    id: 872585,
    title: "Oppenheimer",
    original_language: "en",
    original_title: "Oppenheimer",
    overview:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    poster_path: "/ptpr0kGAckfQkJeJIt8st5dglvd.jpg",
    media_type: "movie",
    genre_ids: [18, 36],
    popularity: 480.927,
    release_date: "2023-07-19",
    video: false,
    vote_average: 8.118,
    vote_count: 6721,
  },
  {
    adult: false,
    backdrop_path: "/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg",
    id: 792307,
    title: "Poor Things",
    original_language: "en",
    original_title: "Poor Things",
    overview:
      "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
    poster_path: "/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
    media_type: "movie",
    genre_ids: [878, 10749, 35],
    popularity: 636.204,
    release_date: "2023-12-07",
    video: false,
    vote_average: 8.119,
    vote_count: 1222,
  },
  {
    adult: false,
    backdrop_path: "/3mpgltEMgPf8zFtPnAWdDVN8ZT1.jpg",
    id: 1056360,
    title: "American Fiction",
    original_language: "en",
    original_title: "American Fiction",
    overview:
      'A novelist fed up with the establishment profiting from "Black" entertainment uses a pen name to write a book that propels him into the heart of hypocrisy and the madness he claims to disdain.',
    poster_path: "/57MFWGHarg9jid7yfDTka4RmcMU.jpg",
    media_type: "movie",
    genre_ids: [35, 18],
    popularity: 92.654,
    release_date: "2023-11-10",
    video: false,
    vote_average: 7.317,
    vote_count: 180,
  },
  {
    adult: false,
    backdrop_path: "/meyhnvssZOPPjud4F1CjOb4snET.jpg",
    id: 940551,
    title: "Migration",
    original_language: "en",
    original_title: "Migration",
    overview:
      "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
    poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
    media_type: "movie",
    genre_ids: [16, 28, 12, 35, 10751],
    popularity: 973.23,
    release_date: "2023-12-06",
    video: false,
    vote_average: 7.647,
    vote_count: 665,
  },
  {
    adult: false,
    backdrop_path: "/8te0oIAuUOxi03RbM1SfL3xUYHB.jpg",
    id: 848538,
    title: "Argylle",
    original_language: "en",
    original_title: "Argylle",
    overview:
      "When the plots of reclusive author Elly Conway's fictional espionage novels begin to mirror the covert actions of a real-life spy organization, quiet evenings at home become a thing of the past. Accompanied by her cat Alfie and Aiden, a cat-allergic spy, Elly races across the world to stay one step ahead of the killers as the line between Conway's fictional world and her real one begins to blur.",
    poster_path: "/siduVKgOnABO4WH4lOwPQwaGwJp.jpg",
    media_type: "movie",
    genre_ids: [35, 28, 80],
    popularity: 145.217,
    release_date: "2024-01-31",
    video: false,
    vote_average: 6.144,
    vote_count: 270,
  },
  {
    adult: false,
    backdrop_path: "/uhUO7vQQKvCTfQWubOt5MAKokbL.jpg",
    id: 693134,
    title: "Dune: Part Two",
    original_language: "en",
    original_title: "Dune: Part Two",
    overview:
      "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
    poster_path: "/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    media_type: "movie",
    genre_ids: [878, 12],
    popularity: 290.85,
    release_date: "2024-02-27",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/pRmF6VBsRnvWCbLB9P80UvZFMyK.jpg",
    id: 1014590,
    title: "Upgraded",
    original_language: "en",
    original_title: "Upgraded",
    overview:
      "Ana is an ambitious intern dreaming of a career in the art world while trying to impress her demanding boss Claire. When she's upgraded to first class on a work trip, she meets handsome Will, who mistakes Ana for her boss– a white lie that sets off a glamorous chain of events, romance and opportunity, until her fib threatens to surface.",
    poster_path: "/9xn7y63VIpUsIVzSP9fYrqJHyl9.jpg",
    media_type: "movie",
    genre_ids: [10749, 35],
    popularity: 971.993,
    release_date: "2024-02-07",
    video: false,
    vote_average: 7.425,
    vote_count: 293,
  },
  {
    adult: false,
    backdrop_path: "/y3sKoItrKZdVEfPeLyoE9m5OG2v.jpg",
    id: 695721,
    title: "The Hunger Games: The Ballad of Songbirds & Snakes",
    original_language: "en",
    original_title: "The Hunger Games: The Ballad of Songbirds & Snakes",
    overview:
      "64 years before he becomes the tyrannical president of Panem, Coriolanus Snow sees a chance for a change in fortunes when he mentors Lucy Gray Baird, the female tribute from District 12.",
    poster_path: "/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg",
    media_type: "movie",
    genre_ids: [18, 878, 28],
    popularity: 844.626,
    release_date: "2023-11-15",
    video: false,
    vote_average: 7.199,
    vote_count: 1779,
  },
  {
    adult: false,
    backdrop_path: "/ehumsuIBbgAe1hg343oszCLrAfI.jpg",
    id: 1022796,
    title: "Wish",
    original_language: "en",
    original_title: "Wish",
    overview:
      "Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.",
    poster_path: "/nesuSdJakNkf0zs7OfoasB6Clxf.jpg",
    media_type: "movie",
    genre_ids: [16, 10751, 14, 12],
    popularity: 919.499,
    release_date: "2023-11-13",
    video: false,
    vote_average: 6.652,
    vote_count: 744,
  },
  {
    adult: false,
    backdrop_path: "/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg",
    id: 346698,
    title: "Barbie",
    original_language: "en",
    original_title: "Barbie",
    overview:
      "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    poster_path: "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    media_type: "movie",
    genre_ids: [35, 12],
    popularity: 256.434,
    release_date: "2023-07-19",
    video: false,
    vote_average: 7.123,
    vote_count: 7373,
  },
  {
    adult: false,
    backdrop_path: "/zLj0peaxy5y2SlC6wNIQ4V0pfqg.jpg",
    id: 1139829,
    title: "Orion and the Dark",
    original_language: "en",
    original_title: "Orion and the Dark",
    overview:
      "A boy with an active imagination faces his fears on an unforgettable journey through the night with his new friend: a giant, smiling creature named Dark.",
    poster_path: "/N2ddXhBX5kqwA9flbm2yqFtX6b.jpg",
    media_type: "movie",
    genre_ids: [16, 10751, 35, 14],
    popularity: 698.175,
    release_date: "2024-02-02",
    video: false,
    vote_average: 6.659,
    vote_count: 229,
  },
  {
    adult: false,
    backdrop_path: "/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg",
    id: 438631,
    title: "Dune",
    original_language: "en",
    original_title: "Dune",
    overview:
      "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    media_type: "movie",
    genre_ids: [878, 12],
    popularity: 377.644,
    release_date: "2021-09-15",
    video: false,
    vote_average: 7.787,
    vote_count: 10091,
  },
  {
    adult: false,
    backdrop_path: "/pWsD91G2R1Da3AKM3ymr3UoIfRb.jpg",
    id: 933131,
    title: "Badland Hunters",
    original_language: "ko",
    original_title: "황야",
    overview:
      "After a deadly earthquake turns Seoul into a lawless badland, a fearless huntsman springs into action to rescue a teenager abducted by a mad doctor.",
    poster_path: "/zVMyvNowgbsBAL6O6esWfRpAcOb.jpg",
    media_type: "movie",
    genre_ids: [878, 28, 18],
    popularity: 2214.237,
    release_date: "2024-01-26",
    video: false,
    vote_average: 6.733,
    vote_count: 422,
  },
];
